### ISSUE TITLE
Using normal properties for the Start/End date columns

### ISSUE THREAD

**Issue by beercsaba** [terryfkjc/EntityFrameworkCore.SqlServer.TemporalTable#3]
Hi!

"This extention will create two shadow properties for the Start/End date column."

Could you please provide some way to use normal properties instead of these shadow ones?
I've tried some ways without success. (defining properties in variuos names, playing with mapping like ignoring, etc...)

I would like to define start and end date properties in my entity classes for these columns and use them for example displaying them on some UI.

Thanks!

**Comment by terryfkjc** [comment]
Hi,

You can use one of the options below

1. Declare properties with name `SysStartTime ` and `SysEndTime `
```c#
public class Post
{
    public int Id { get; set; }
    public string Name { get; set; }

    public DateTime SysStartTime { get; set; } 
    public DateTime SysEndTime { get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.Entity<Post>(e =>
	{
		e.HasTemporalTable();
	}
}
```
2. Custom property name

```c#
public class Post
{
	public int Id { get; set; }
	public string Name { get; set; }

	public DateTime StartTime { get; set; }
	public DateTime EndTime { get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.Entity<Post>(e =>
	{
		e.HasTemporalTable();

		e.Property(p => p.StartTime)
			.HasColumnName("SysStartTime") //map to SysStartTime column.
			.ValueGeneratedOnAddOrUpdate(); //let EF do not insert or update value

		e.Property(p => p.EndTime)
			.HasColumnName("SysEndTime")
			.ValueGeneratedOnAddOrUpdate();
	}
}

```

Hope this help!

**Comment by beercsaba** [comment]
Hi,
Thanks for your response!

Columns are called RowValidFrom and RowValidTo in our tables.
In the 2nd option column names must match these SysStartTime and SysEndTime?

**Comment by terryfkjc** [comment]
Yes

**Comment by beercsaba** [comment]
The i've tried to adjust data model in this way:
`modelBuilder.Entity(type, entity => entity.HasTemporalTable(config => { config.StartDateColumn(temporalFromColumn); config.EndDateColumn(temporalToColumn); }));`
for each related entity types, where TemporalFromColumn = "RowValidFrom";  and TemporalToColumn = "RowValidTo";

It did not worked, because generated sql statements contained 2 occurences of these start/end colums named 'RowValidFrom' and 'RowValidFrom1'.

Is there any way to use 'custom' column names, or we must adjust our column names to these fixed ones (SysStartTime and SysEndTime)?

**Comment by terryfkjc** [comment]
You can configure DbContext in this way

```c#
modelBuilder.Entity<Post>(e =>
{
	e.HasTemporalTable(config =>
	{
		config.StartDateColumn("RowValidFrom");
		config.EndDateColumn("RowValidTo");
	});

	e.Property(p => p.StartTime)
		.HasColumnName("RowValidFrom")
		.ValueGeneratedOnAddOrUpdate();

	e.Property(p => p.EndTime)
		.HasColumnName("RowValidTo")
		.ValueGeneratedOnAddOrUpdate();
		
}

```

**Comment by beercsaba** [comment]
i will try it again soon. :)

**Comment by beercsaba** [comment]
![image](https://user-images.githubusercontent.com/24902130/131875812-7ab04f18-812c-4e04-945b-1ce1ebbda01f.png)

Unfortunately beyond the explicitly defined (non-shadow) RowValidFrom and RowValidTo properties there are the implicitly defined (shadow) SysStartTme and SysEndTime properties in the model of this entity type, and this causes this error when creating a new entity: "An item with the same key has already been added. Key: RowValidTo".

Maybe because both propeties references the same column (name).

DBContext configuration:
            modelBuilder.Entity(type, entity => entity.HasTemporalTable(config => { config.StartDateColumn(temporalFromColumn); config.EndDateColumn(temporalToColumn); }));
            modelBuilder.Entity(type, entity => entity.Property(typeof(DateTime), nameof(RowValidFrom)).HasColumnName(temporalFromColumn).ValueGeneratedOnAddOrUpdate());
            modelBuilder.Entity(type, entity => entity.Property(typeof(DateTime), nameof(RowValidTo)).HasColumnName(temporalToColumn).ValueGeneratedOnAddOrUpdate());

Is this an expected behaviour?

other problem arises when i use EF Core PowerTools to create my data model with reverse engineering. 
model is generated in this way:
```
entity.Property(e => e.RowValidFrom).HasPrecision(2);
entity.Property(e => e.RowValidTo).HasPrecision(2);
```
columns are defined in this way:
[RowValidFrom]   DATETIME2(2)  GENERATED ALWAYS AS ROW START
[RowValidTo]     DATETIME2(2)  GENERATED ALWAYS AS ROW END

while building the model this exception comes:
System.InvalidOperationException: ''ASB.RowValidTo' and 'ASB.SysEndTime' are both mapped to column 'RowValidTo' in 'ASBTable' but are configured with different precision ('' and '2').' 
Thins means implicitly defined properties has no precision set, as we can see in TemporalConfiguration class:
```
        public virtual TemporalConfiguration StartDateColumn(string column)
        {
            this.EntityTypeBuilder
                .Property<DateTime>(TemporalAnnotationNames.DefaultStartTime)
                .SetStartDateColumn(column)
                .ValueGeneratedOnAddOrUpdate();

            return this;
        }
```

I guess it is not so easy to fix these problems, so maybe it's better to use the default column names in our tables.
Do You agree?

**Comment by terryfkjc** [comment]
> Unfortunately beyond the explicitly defined (non-shadow) RowValidFrom and RowValidTo properties there are the implicitly defined (shadow) SysStartTme and SysEndTime properties in the model of this entity type, and this causes this error when creating a new entity: "An item with the same key has already been added. Key: RowValidTo".

I can't reproduce this error with my sample code, here is my setup:

```c#
public class Post
{
	public int Id { get; set; } //this is the primary key
	public string Name { get; set; }

	public DateTime StartTime { get; set; }
	public DateTime EndTime { get; set; }
}

//configure db context
modelBuilder.Entity<Post>(e =>
{
	e.HasTemporalTable(config =>
	{
		config.StartDateColumn("RowValidFrom");
		config.EndDateColumn("RowValidTo");
	});

	e.Property(p => p.StartTime)
		.HasColumnName("RowValidFrom")
		.ValueGeneratedOnAddOrUpdate();

	e.Property(p => p.EndTime)
		.HasColumnName("RowValidTo")
		.ValueGeneratedOnAddOrUpdate();
}

//the only property I can set is the Name property.
//Id, StartTime and EndTime are generated properties
//It will be better if you can mark the start/end date as readonly as it should be set by outside of the class
var _CSharp = new Post()
{
	Name = "Welcome to C#"
};

var _VB = new Post()
{
	Name = "Welcome to VB"
};

postDbContext.Posts.AddRange(_CSharp, _VB);
await postDbContext.SaveChangesAsync(); //ok
```

> columns are defined in this way:
[RowValidFrom] DATETIME2(2) GENERATED ALWAYS AS ROW START
[RowValidTo] DATETIME2(2) GENERATED ALWAYS AS ROW END

The Start/End date in temporal table must be specified as the maximum value for a given datetime/datetime2 precision.
You may need to remove the `HasPrecision(2)`. For the temporal table requirements, you can refer to [here](https://docs.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table?view=sql-server-ver15#important-remarks-3). 
Currently datetime2 is used when creating the Start/End date columns.

**Comment by beercsaba** [comment]
Hi,

I assume, you are right! :)

We have changed our column names to SysStartTime and SysEndTime and everything works fine.

Thanks for all!
